apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
      id: "2"
  template:
    metadata:
      labels:
        app: kafka2
        id: "2"
    spec:
      containers:
      - name: kafka2
        image: bitnami/kafka
        ports:
        - containerPort: 9094
        env:
        - name: KAFKA_CFG_PORT
          value: "9094"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: PLAINTEXT
        - name: KAFKA_CFG_TLS_CLIENT_AUTH
          value: none
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zoo0:2181
        - name: KAFKA_CFG_BROKER_ID
          value: "2"
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9094
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://34.122.1.97:9094
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"