apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
      id: "1"
  template:
    metadata:
      labels:
        app: kafka1
        id: "1"
    spec:
      containers:
      - name: kafka1
        image: gcr.io/molten-reserve-317003/broker1_image:ssl-empty1
        ports:
        - containerPort: 9093
        env:
        - name: KAFKA_CFG_LISTENERS
          value: SSL://:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: SSL://34.70.95.183:9093
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: SSL
        - name: KAFKA_CFG_PORT
          value: "9093"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zoo0:2182
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"