apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-zoo
spec:
  storageClassName: "mystcls"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: data-claim-zoo
  gcePersistentDisk:
    pdName: data-volume-zoo
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim-zoo
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi