apiVersion: v1
kind: ConfigMap
metadata:
  name: ftp-configmap
data:
  # property-like keys; each key maps to a simple value
  users.conf: |
    mk1:demo:1020:100:/uploads
    mk2:demo:1021:100:/uploads
    mk3:demo:1022:100:/uploads