apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka0
      id: "0"
  template:
    metadata:
      labels:
        app: kafka0
        id: "0"
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: kafka0
        image: gcr.io/molten-reserve-317003/broker0_image:new6
        volumeMounts:
        - mountPath: "/tmp/broker0"
          name: data-broker0
          subPath: broker0-data
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_LISTENERS
          value: SASL_SSL://34.66.67.234:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: SASL_SSL://34.66.67.234:9092
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: SSL
        - name: KAFKA_CFG_PORT
          value: "9092"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zoo0:2182
        - name: KAFKA_CFG_BROKER_ID
          value: "0"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
      volumes:
      - name: data-broker0
        persistentVolumeClaim:
          claimName: data-claim-brokers-0