apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv-brokers
spec:
  storageClassName: "mystcls"
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: data-claim-brokers
  gcePersistentDisk:
    pdName: data-volume-brokers
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim-brokers
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi