apiVersion: v1
kind: Service
metadata:
  name: kafka-s2
  labels:
    name: kafka2
spec:
  ports:
  - port: 9094
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka2
  type: LoadBalancer