apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
      id: "1"
  template:
    metadata:
      labels:
        app: kafka1
        id: "1"
    spec:
      containers:
      - name: kafka1
        image: gcr.io/molten-reserve-317003/broker1_image:39
        ports:
        - containerPort: 9093
        env:
        - name: KAFKA_CFG_LISTENERS
          value: SASL_SSL://34.70.95.183:9093
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: SASL_SSL://34.70.95.183:9093
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: SSL