apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-b0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka0
      id: "0"
  template:
    metadata:
      labels:
        app: kafka0
        id: "0"
    spec:
      containers:
      - name: kafka0
        image: gcr.io/molten-reserve-317003/broker0_image:11
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_LISTENERS
          value: SASL_SSL://34.66.67.234:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: SASL_SSL://34.66.67.234:9092
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: SASL_SSL
        - name: KAFKA_ZOOKEEPER_USER
          value: broker-admin
        - name: KAFKA_ZOOKEEPER_PASSWORD
          value: demokafka
        - name: KAFKA_ZOOKEEPER_TLS_KEYSTORE_PASSWORD
          value: demokafka
        - name: KAFKA_ZOOKEEPER_TLS_TRUSTSTORE_PASSWORD
          value: demokafka
