apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  storageClassName: "mystcls"
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: data-claim
  gcePersistentDisk:
    pdName: data-volume
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  storageClassName: "mystcls"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi