apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-d0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-0
  template:
    metadata:
      labels:
        app: zookeeper-0
    spec:
      containers:
      - name: zoo0
        image: gcr.io/molten-reserve-317003/zoo_image:exp1
        ports:
        - containerPort: 2181
        - containerPort: 2182
        env:
        - name: ZOO_ENABLE_AUTH
          value: "yes"
        - name: ZOO_LOG_LEVEL
          value: ALL
        - name: ZOO_TLS_CLIENT_ENABLE
          value: "true"
        - name: ZOO_TLS_PORT_NUMBER
          value: "2182"
        - name: ZOO_TLS_CLIENT_KEYSTORE_FILE
          value: /bitnami/zookeeper/certs/zookeeper.keystore.jks
        - name: ZOO_TLS_CLIENT_KEYSTORE_PASSWORD
          value: demokafka
        - name: ZOO_TLS_CLIENT_TRUSTSTORE_FILE
          value: /bitnami/zookeeper/certs/zookeeper.truststore.jks
        - name: ZOO_TLS_CLIENT_TRUSTSTORE_PASSWORD
          value: demokafka
        - name: ZOO_TLS_CLIENT_AUTH
          value: need