# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pred
  template:
    metadata:
      labels:
        app: ml-pred
    spec:
      containers:
        - name: ml-model-predictor
          image: gcr.io/molten-reserve-317003/predict:latest
          env:
            name: PORT
            value: 8080
          volumeMounts:
            - mountPath: "/mnt/c"
              name: ftp-volume
          ports:
          - containerPort: 8080
      volumes:
        - name: ftp-volume
          # This GCE PD must already exist.
          persistentVolumeClaim:
            claimName: data-claim-ftp
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-s1
  labels:
    name: kafka1
spec:
  type: LoadBalancer
  selector:
    app: ml-pred
  ports:
    - port: 80
      targetPort: 8080
